# Work-life balance

Please take an active interest in your well-being and your private life. You should protect your weekends, evening, federal holidays etc. - you will never be expected to work during these times. 

## Working hours, home office, and reachability

There is no "clocking in and out" or recording of your physical presence in the office. You are ultimately free to work when and where you like. Working from home is fine.

I don't keep Outlook or Slack on my phone, and you are not expected to, too. However, during work weeks, please maintain a state where you can be reached within a day's notice, i.e. check your e-mail and Slack notifications from your computer at least once a day. [Focused "deep" work](https://blog.doist.com/deep-work/) is very important and increasingly difficult to schedule - it is absolutely OK to protect your time and disconnect for a few hours to have full focus on a difficult bit of work.

## Vacation

You are officially granted two weeks of paid vacation per year per Hopkins policy. I do not object to you taking time off beyond those two weeks which I consider to be the bare minimum (after all, I've been socialized in Europe). However, there are a few agreements I would like you to respect:

- Please inform me about your vacation plans as soon as you can. If your planned vacation time coincides with a grant deadline or the hot seat phase of a project, I need to be able to plan accordingly and well ahead of time.

- Please make sure that your regular duties (scheduling and scanning participants, organizing meetings etc.) are taken care of by someone else during your absence.

- You are not required to monitor your e-mail, Slack, etc. during your vacation time. I will only ever consider contacting you through your private phone in the case of absolute emergency.
