# Life in Baltimore and at Hopkins

The [Johns Hopkins Postdoctoral Association](https://www.jhpda.jhmi.edu/) advocates for the interests of postdocs at JHMI, organizes a lot of fun events, and is a nice way to meet new people. The [Cooley Center](https://www.jhmifitness.com) has affordable gym memberships and offers intramural sports leagues and classes. [Welch Medical Library](https://welch.jhmi.edu/) is your first stop for book loans, literature research, and the meta-analysis tool Covidence. 

Sign up for a free library card from the [Enoch Pratt Free Library](https://www.prattlibrary.org/) and get access to their amazing physical and digital catalogue. Become a member at [Station North Tool Library](https://www.stationnorthtoollibrary.org/) to borrow power tools and gain access to the open workshop. 

Social leagues like [Volo Sports](https://www.volosports.com/) are the preferred way to play your favourite sports and meet new people. 

[Baltimore Banner](https://www.thebaltimorebanner.com/) and [Baltimore Beat](https://baltimorebeat.com/) are two exciting additions to the (alt-)newspaper space in Baltimore. The latest cultural news and events can also be found in [Baltimore Magazine](https://www.baltimoremagazine.com/), [Baltimore Fishbowl](https://baltimorefishbowl.com/), and the [baltshowplace tumblr](https://baltshowplace.tumblr.com/). 

Amazing annual festivals in and around Baltimore include [Artscape](https://www.artscape.org/), [HONfest](http://honfest.net/), [Baltimore Book Festival](https://brilliantbaltimore.com/baltimore-book-festival/), [Baltimore Restaurant Week](http://baltimorerestaurantweek.com/), [Light City](https://brilliantbaltimore.com/light-city/), and many more. Look out for small neighborhood festivals as well.

The best museums include [The Walters](https://thewalters.org/), the [Baltimore Museum of Art](https://artbma.org/), the [American Visionary Art Museum](https://www.avam.org/), and the[Reginald F. Lewis Museum of Maryland African American History & Culture](https://www.lewismuseum.org/). 

Excellent neighborhood-owned bookshops worth supporting are [Greedy Reads](https://greedyreads.com/), [Charm City Books](https://charmcitybooks.com/), [the Ivy Bookshop](https://www.theivybookshop.com/) - and you can get books for free every month from the big warehouse at [The Book Thing](https://bookthing.org/)!! (Some recommended books to learn more about the history of Baltimore: [The Black Butterfly](https://www.goodreads.com/en/book/show/54320814-the-black-butterfly), [Not In My Neighborhood](https://www.goodreads.com/book/show/7489945-not-in-my-neighborhood), [Baltimore: A Political History](https://www.goodreads.com/en/book/show/33032386-baltimore))

Movie theatres include the [Charles Theatre](https://thecharles.com), the Parkway Theatre (https://mdfilmfest.com/), and the [Senator Theatre](https://thesenatortheatre.com/). 

Good day trip getaways into nature: [Rocks State Park](https://dnr.maryland.gov/publiclands/pages/central/rocks.aspx), [Patapsco Valley State Park](https://dnr.maryland.gov/publiclands/pages/central/patapsco.aspx), [Gunpowder Falls State Park](https://dnr.maryland.gov/publiclands/pages/central/gunpowder.aspx), [Frederick](https://www.visitfrederick.org/). 

