--- 
title: "specfitlab handbook"
author: "Georg Oeltzschner"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: krantz
link-citations: yes
colorlinks: yes
lot: yes
lof: yes
fontsize: 12pt
github-repo: schorschinho/specfitlab-handbook
description: "This is the lab handbook of the specfitlab."
---

# Welcome {-}

Welcome to the lab handbook of the [specfitlab](https://www.specfitlab.com), the research group overseen by Georg Oeltzschner (that is me).

I began writing the lab handbook when I was just beginning my position as tenure-track faculty in 2021, right when I started paying the salary of someone else for the first time in my life. Writing the lab handbook meant actively reflecting on the healthy, productive, and fun research environment I would like the team to become - a reflection certainly shaped by my own experiences as a trainee. By writing it down and making it public, I want to hold myself accountable for my commitments and my expectations.

The lab handbook is a written version of everything that I have frequently found to be transmitted informally. It wants to be a clear and transparent list of every group member's rights, commitments, and expectations, including my own. It is a database of standard operating procedures within the group, but also within our division, department, and institution. Finally, it is a (hopefully well-maintained) repository of useful resources and information for our research and the day-to-day life and work in the group.

The lab handbook is supposed to be a living document, expected to morph and mature over time, as our perspectives and views will change. Some aspects may become obsolete, other issues that the lab handbook had not anticipated or planned for will need addressing. If you have suggestions on adding, removing, or clarifying parts of the lab handbook - please do not hesitate to speak to me or submit a pull request through GitHub.

I'm beyond happy and proud to have the privilege of being in a team with you.

```{block2, type='flushright', html.tag='p'}
Georg Oeltzschner
```
